### ISSUE TITLE
这个是把keeganlee那个大哥的文章实现里嘛

### ISSUE THREAD

**Issue by lycaste** [wangbinzero/kunkka-match#1]
大佬 您是将他的文章实现的嘛。还是你们是一个人

**Comment by wangbinzero** [comment]
是的，年前实现的。最近由于疫情，没有动了

yaohao <notifications@github.com> 于2020年2月2日周日 下午7:32写道：

**Comment by wangbinzero** [comment]
> 大佬 您是将他的文章实现的嘛。还是你们是一个人

不是一个人。我是看他的文章来实现的
