### ISSUE TITLE
请问有使用文档吗？

### ISSUE THREAD

**Issue by ygcool** [wangbinzero/kunkka-match#2]
例如我通过其他语言的程序，如何推送订单至这个撮合引擎，再如何获取成交信息和未成交订单列表等等。感谢！

**Comment by wangbinzero** [comment]
使用MQ进行推送。订单信息目前存储在内存中。可以自行看代码改造

**Comment by wangbinzero** [comment]
> 例如我通过其他语言的程序，如何推送订单至这个撮合引擎，再如何获取成交信息和未成交订单列表等等。感谢！

使用MQ进行推送。订单信息目前存储在内存中。可以自行看代码改造
